### ISSUE TITLE
Kubernetes pods only get auth token on startup

### ISSUE THREAD

**Issue by bschlaman** [google/exposure-notifications-server#1213]
### TL;DR
For the azure driver, Pods only get authentication token at startup.  This means that if the pod is not restarted for a long stretch of time, the token will expire after 60 days, causing the pod to fail requests to storage, etc.

**Expected behavior**
Get authentication token for every call, or at some more frequent interval.

**Observed behavior**
Auth token only refreshed only upon startup.

### Reproduction

Keep pod running for 60 days

**Comment by bschlaman** [comment]
cc: @jpflueger

**Comment by mikehelmick** [comment]
is this across all services (key vault and storage) or just specific to storage?

**Comment by bschlaman** [comment]
I discovered the issue in storage - but I'm assuming this goes for key vault as well.  @jpflueger does that sound right?

**Comment by sethvargo** [comment]
We definitely don't want to do the auth token dance _every_ time. We use the standard Azure client libraries. IMO, those libraries should handle re-auth (that's how the Google ones work). Alternatively, schedule a pod restart every ~45 days?

@nmiodice or @jpflueger can you comment? If there's some flag we need to set on the client libraries to regularly refresh, let us know.

**Comment by nmiodice** [comment]
@sethvargo there is code in place to support a token refresh. See here for more info: https://github.com/google/exposure-notifications-server/blob/main/internal/storage/azure_blobstore.go#L48-L74. For Azure Storage, it is a little bit more manual than other services but the general pattern should suite our needs.

@bschlaman, it looks like based on the implementation, if a token refresh ever fails then the refresh won't be attempted again. My first debugging step would be to see if `failed to refresh access token` appears in the logs for the service in question. If you see that, then it is likely that a single failure resulted in the token never attempting to be refreshed. This is a scenario in which I think it would be OK to log, but otherwise disregard the error.

More info from the SDK documentation for `azblob.NewTokenCredential`

> Your tokenRefresher function must return a time.Duration indicating how long the TokenCredential object should wait before calling your tokenRefresher function again. If your tokenRefresher callback fails to refresh the token, you can return a duration of 0 to stop your TokenCredential object from ever invoking tokenRefresher again. Also, oen way to deal with failing to refresh a token is to cancel a context.Context object used by requests that have the TokenCredential object in their pipeline.

**Comment by bschlaman** [comment]
Unfortunately this happened a while back, so I won't be able to check the logs

**Comment by sethvargo** [comment]
Thanks @nmiodice. It sounds like we might not need a code change here?

@bschlaman can you share more of the symptoms? Was this just a log message or was there legitimate production impact?

**Comment by nmiodice** [comment]
> Unfortunately this happened a while back, so I won't be able to check the logs

How long back? I don't have access to check the logs myself, but the retention should be at least 90 days, I think. It's been a while :).

@sethvargo & @bschlaman , IMO it is not a bad idea to not return `0` if the token refresh fails, otherwise the system will stop working correctly if the token refresh fails only one time.

**Comment by sethvargo** [comment]
@nmiodice what is a better value to return? 30s or 5m?

**Comment by nmiodice** [comment]
The values in https://github.com/google/exposure-notifications-server/pull/1218 are reasonable. A quick retry time is suitable since any token refresh failure should be transient
