### ISSUE TITLE
Improve CloudSchedulerJobFailed playbook

### ISSUE THREAD

**Issue by mariliamelo** [google/exposure-notifications-server#1429]
We should improve [CloudSchedulerJobFailed playbook](https://github.com/google/exposure-notifications-server/blob/main/docs/playbooks/alerts/CloudSchedulerJobFailed.md) and add information for each cloud scheduler job we have (similar to what we have in the [Verification Server](https://github.com/google/exposure-notifications-verification-server/blob/main/docs/playbooks/alerts/CloudSchedulerJobFailed.md)).

I have most of the information for most jobs, but still need insight into `export-importer-cschedule` and `export-importer-worker`. 

@sethvargo can you add some info about what these 2 jobs are doing?

**Comment by sethvargo** [comment]
`export-importer-cschedule` invokes the `/schedule` endpoint of the export-import service. It downloads and parses the remote index file, applies any rewrite rules, and stores the results in the database. It does _not_ download the actual export zip files themselves, just the references in the index. It syncs index files and applies rewrite rules. The `export-importer-worker` uses the data synced by cschedule to actually download import the export files. They work together, but are separate processes because the worker has retry logic and can handle partial success.

**Comment by sethvargo** [comment]
All background jobs have been refactored to be forward-progress alerts. This is now obsolete.
