### ISSUE TITLE
consider application level encryption of key data in the database

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#291]
**Is your feature request related to a problem? Please describe.**

Allows for a separation of responsibilities and someone with raw database access, but not KMS access can't observe the data in the database.

**Describe the solution you'd like**

An envelop encryption solution seems best due to the high cluster of decrypt operations that would be needed on export generation.

**Describe alternatives you've considered**

We should still consider if this is necessary given the amount of effort. This is one avenue to combat insider risk, but if ACLs aren't configured correctly this provides little benefit.

/kind enhancement

**Comment by sethvargo** [comment]
My preference would be to leverage [CMEK on Cloud SQL here](https://cloud.google.com/sql/docs/mysql/configure-cmek) and allow anyone implementing this server to choose their own encryption (if they want).

CMEK doesn't quite solve the problem, since the Cloud SQL service account is the authorizing principal though.

**Comment by radisef347** [comment]
![alt text](https://images.pornpics.com/1280/201901/08/2693239/2693239_103_339a.jpg)
