### ISSUE TITLE
Should we vendor dependencies?

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-server#422]
We're currently using Go modules, so dependencies are resolved as-needed. However, if a dependency were to ever go away, that could introduce instability. Furthermore, on CI and CD, we spend the additional CPU and bandwidth _every time_ to resolve and download all the modules. 

We could, instead, vendor the dependencies (`go mod vendor`) and still use Go modules to maintain the dependency list. It would guarantee that this repo is always buildable and make our CI/CD faster since the dependencies would all be included in the initial source download.

On the downside, it would bloat the repo and PRs, especially when changing dependencies.

**Comment by johanbrandhorst** [comment]
The use cases for vendoring in an open source project are pretty small nowadays. To counter your points:
* Dependencies "going away" is much less likely to happen since the introduction of the official (and third party) Go proxies: https://github.com/golang/go/wiki/Modules#are-there-always-on-module-repositories-and-enterprise-proxies. These hold complete copies of the source, so even if the dependency were to go away from the originally hosted location, it'll be available there.
* If the time spent downloading and unpacking dependencies in CI and CD is a concern, we should sooner explore caching the go cache (and modules cache) directory. This would not only help with download speed but also caches build artifacts and even tests, speeding up the general execution of the pipelines.

**Comment by mikehelmick** [comment]
-1 to vendoring.

I wonder if we can throw more resources at the prow instance.

**Comment by sethvargo** [comment]
It’s not prow, it’s Cloud Build

**Comment by mikehelmick** [comment]
/close

@sethvargo - you know what to do if you disagree 😃
