### ISSUE TITLE
implement TENP

### ISSUE THREAD

**Issue by ysalomon** [google/exposure-notifications-server#431]
We have recently published the [Threat Exposure Notification Protocol](https://tenprotocol.org/), an RFC proposal, also available on [Github](https://github.com/tenprotocol/tenprotocol), together with an initial [server reference implementation](https://github.com/tenprotocol/tenprotocol-server/tree/master).

Our objective was to solve the following key limitations:

1. Interoperability across decentralized applications to address the potential fragmentation of data, by supporting a standard for service discovery and basic API functionality.
2. A general framework to support different tracing technologies and standards, as well as a plurality of threats. 

We are keen to collaborate and explore ways in which TENP can potentially be supported here.

**Comment by sethvargo** [comment]
Hi @ysalomon 

Thank you for opening an issue. Our API is open (it's this repo), and we've published our server and client API interactions in partnership with Apple at https://www.google.com/covid19/exposurenotifications/ since mid-April. 

If you have specific areas where you think our implementation differs from TENP, please feel free to open issues or submit Pull Requests to highlight those differences to discuss them on a case-by-case basis. Please do note that we have to maintain API compatibility with existing clients.

This is a rapidly evolving space as the needs of epidemiologists, governments, and public health authorities (PHAs) evolve. Our primary goal and objective is to enable PHAs to reduce the spread of the virus. Unfortunately participating RFC reviews is not currently a priority at the moment. Thanks and have a great day!
