### ISSUE TITLE
Public Health Authority Diagnosis Verification Protocol

### ISSUE THREAD

**Issue by xyz23** [google/exposure-notifications-server#545]
### Question
1. Who is hosting the PIN server (PIN verification server), will it be PHA or will it part of exposure server in future?

1. Is there a sample code for PIN verification server?

1.  High Level Flow

    > 2. The user enters the PIN code on their App
    > 3. The app creates a HMAC value that combines the TEKs from the device along with calculated transmission risk value, rolling period start and rolling period count values (the key data + metadata). These values are sent to the PHA server that issued the PIN.
    > 4. If the PIN is valid, the PHA issues a JWT that is signed using ECDSA over the P-256 elliptic curve with SHA-256 as a hash function. The JWT includes additional claims about the data (see below).

1. Why do we have 3-step process?  We could have directly generated JWT when valid PIN is sent else return error.

1. How do exposure server handle "replay" attack in this new architecture? (can you please point out in the code?)

**Comment by sethvargo** [comment]
1. The current plan is for a PHA or other entity to run the PIN server. This provides a separation of concerns, as the PIN server could require some authorization or PII exchange, and this server specifically forbids handling of such information.

1. PIN _generation_ occurs by a PHA server. There is not yet an open source PIN _generation_ server. PIN _verification_ is already available in this repository.

1. Re: 3 step process. The PHA server never receives the TEKs, it only receives a request for a PIN and a signing request with an HMAC of the TEKs (+ other data). I'm not sure how you would reduce this to less than 3 steps?

1. Re: reply. The JWT is signed and on the HMAC of the TEKs (+ other data). The only replay attack would be a user sending the exact same set of keys multiple times. If they change any of the keys, the signature will no longer be valid, and the publish will be silently rejected.

**Comment by mikehelmick** [comment]
We are still evolving the requirements for the PIN verification server and will have a reference design and reference implementation to share soon. Design will be published before the full server implementation.

For the replay attack. The verification certificate (the JWT) should be issued with a short validity time window. The is controlled by the standard claims, `iat` and `exp`.

Since the specific TEKs and timing information are part of the HMAC value that is signed, any reply of the certificate could only ever present the exact same date. So this narrows the window of replay and mitigates the effects. It is not possible to compromise a certificate and use it to upload a different set of keys.

Let us know if you have additional questions around this.

/close
