### ISSUE TITLE
How are keys being selected for batching/export creation?

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#642]
@gurayAlsac after the last bug fix we were able to succefully create a batch of files from uploaded keys, thanks.

We reset the entire DB to run another test round and were able to submit keys to "exposure" service but they they keep getting skipped for batching with no errors.

We have set the export config window to 2 months for testing purposes, index files gets created but no new batches even after deleting all old entries from DB.

Note : we tried invoking the exposure-batch creation jobs manually to test (no errors but no output)

A few hours later the job runs and files are created.

We noticed that the query for selecting the keys always shows t-3 hours from the current time (current time = the created_time) of the keys.

Can you please explain what we might be missing or is this something that needs to be checked in the batching query?

![Screenshot 2020-06-17 18 29 26](https://user-images.githubusercontent.com/666788/84967553-1a0a0200-b0c9-11ea-95d0-730baef16f4d.png)

**Comment by mikehelmick** [comment]
Hi @sherifkozman 

This is an intentional embargo to ensure that keys are not released until they are held for 2 hours after their batch window closes.

See the [MIN_WINDOW_AGE](https://github.com/google/exposure-notifications-server/blob/master/internal/export/config.go#L49) var on the export service.

So with the default value and the export period you have, any gaps from the last created export batch until now - 2h will have a batch created for it. https://github.com/google/exposure-notifications-server/blob/71f5ac30922182cb5ed98610753ddff6343c42cb/internal/export/batcher.go#L102

If you want to release keys even faster (for testing purposes only), there are other flags you can tweak to get this down to around a 5-10 minute turnaround.

I'll leave this open - let me know if this answers your question or if I can help with anything else.

/assign

**Comment by sherifkozman** [comment]
@mikehelmick That explains it all thank you.
One more question related to keys and the requirement to sign them.
Documentation states : 
"If the signing key is invalid, or if the key is not shared with Google and Apple, the Exposure Notification API will not invoke matching on the export."
If keys are not signed or signed with a key that is not shared during development and testing will this affect client's behaviour during testing ?
i.e : is it mandatory to share public keys with google even during development ?

**Comment by gurayAlsac** [comment]
During development you can take advantage of the debug mode to disable signature verification. Settings > Google > Covid-19 Exposure Notifications > Debug Mode > Enable diagnosis key file signature check

**Comment by sherifkozman** [comment]
@gurayAlsac i assume you are referring to android settings here?

**Comment by gurayAlsac** [comment]
Right

**Comment by gurayAlsac** [comment]
FYI, Debug Mode documentation is now available at https://developers.google.com/android/exposure-notifications/partners/debug-mode

**Comment by sherifkozman** [comment]
@gurayAlsac The link is a 404

**Comment by gurayAlsac** [comment]
Ah sorry. The link is currently available to certain allowlisted partners, but will be public in a week or so.

**Comment by sherifkozman** [comment]
@gurayAlsac any updates about the above link being public ?

**Comment by zssz** [comment]
@sherifkozman reach out to your Google EN contact person. Also, be sure to be logged in with the allowlisted email address when you visit the link above.

**Comment by gurayAlsac** [comment]
> @gurayAlsac any updates about the above link being public ?

It should be public now at https://developers.google.com/android/exposure-notifications/debug-mode

Feel free to create a new issue if its not accessible.
