### ISSUE TITLE
Exposure Key encoding

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#766]
Mobile Devs have been asking how key_data is being encoded ? i.e (UTF8 , ASCII, etc.. )
@mikehelmick

**Comment by mikehelmick** [comment]
For upload or download?

**Comment by mikehelmick** [comment]
I'm assuming upload - Keys are base64 encoded.

https://github.com/google/exposure-notifications-server/blob/main/pkg/api/v1alpha1/exposure_types.go#L96

**Comment by sherifkozman** [comment]
download please

**Comment by mikehelmick** [comment]
The download file format is here
https://developers.google.com/android/exposure-notifications/exposure-key-file-format

Since it is a protocol buffer, keys are available as byte array.

That being said - there is no reason that a mobile app needs to crack open this file. It's possible, but there it is not necessary. The bundle just needs to be handed to the OS for matching.

**Comment by mattThousand** [comment]
@mikehelmick for a key with a `keydata` property such as this `rb[\220\255?\202\3115\355QTE\266\23`, how do you recommend converting this into a byte array?
